name: Continuous Integration - PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install node modules
        run: |
            npm ci

      - name: Run unit tests
        run: |
            npm test